workaround recent changes in Docker base image or pip that breaks cffi
```
.../cairocffi_2993bb4b6d1e4a1d8e75f1f583f3a806/.eggs/cffi-1.17.1-py3.10-linux-x86_64.egg/cffi/cparser.py", line 7, in <module>
          import pycparser
      ModuleNotFoundError: No module named 'pycparser'
```